version: '3.8'

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  server1:
    build:
      context: .
      dockerfile: Dockerfile.scalable
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVER_ID=server-1
      - SERVER_REGION=us-east
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - METERED_TURN_USERNAME=${METERED_TURN_USERNAME}
      - METERED_TURN_CREDENTIAL=${METERED_TURN_CREDENTIAL}
      - METERED_TURN_SERVERS=${METERED_TURN_SERVERS}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  server2:
    build:
      context: .
      dockerfile: Dockerfile.scalable
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVER_ID=server-2
      - SERVER_REGION=us-east
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - METERED_TURN_USERNAME=${METERED_TURN_USERNAME}
      - METERED_TURN_CREDENTIAL=${METERED_TURN_CREDENTIAL}
      - METERED_TURN_SERVERS=${METERED_TURN_SERVERS}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  server3:
    build:
      context: .
      dockerfile: Dockerfile.scalable
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVER_ID=server-3
      - SERVER_REGION=us-west
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - METERED_TURN_USERNAME=${METERED_TURN_USERNAME}
      - METERED_TURN_CREDENTIAL=${METERED_TURN_CREDENTIAL}
      - METERED_TURN_SERVERS=${METERED_TURN_SERVERS}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data: